services:
  web:
    build:
      context: .
    restart: unless-stopped
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.productivity-proposal-cohrvj-9-web.rule=Host(`proposal.arkane.my.id`)
      - traefik.http.routers.productivity-proposal-cohrvj-9-web.entrypoints=web
      - traefik.http.services.productivity-proposal-cohrvj-9-web.loadbalancer.server.port=3000
      - traefik.http.routers.productivity-proposal-cohrvj-9-web.service=productivity-proposal-cohrvj-9-web
      - traefik.enable=true
    networks:
      dokploy-network: {}
      default: {}
networks:
  dokploy-network:
    external: true
